name: Release

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100-rc.1

      - name: Setup NuGet 6.x
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: 6.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Package
        run: |
          dotnet pack ./src/MediatR.Azure.EventGrid.Serialization/MediatR.Azure.EventGrid.Serialization.csproj --configuration Release --no-build --output ./artifacts
          dotnet pack ./src/MediatR.Azure.EventGrid/MediatR.Azure.EventGrid.csproj --configuration Release --no-build --output ./artifacts

      - name: Push to NuGet.org
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        working-directory: ./artifacts

      - name: Push to GitHub
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
        working-directory: ./artifacts

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts/**/*
